import { Injectable } from '@nestjs/common';
import {
  LlmAgent,
  Runner,
  InMemorySessionService,
  isFinalResponse,
} from '@google/adk';
import { Content } from '@google/genai';
import { searchBooksTool } from './tools/books.tool';
import { createListsTools } from './tools/lists.tool';
import { UserService } from '../user/user.service';

const APP_NAME = 'bookmind';

@Injectable()
export class ChatbotService {
  private sessionService = new InMemorySessionService();
  private runner: Runner;

  constructor(private userService: UserService) {}

  private createAgent(userId: string): LlmAgent {
    const listsTools = createListsTools(userId, this.userService);

    return new LlmAgent({
      name: 'bookmind_agent',
      model: 'gemini-2.5-flash',
      description:
        'A book assistant that helps users discover and manage books',
      instruction: `
        You are BookMind, a helpful book assistant. You help users:
        - Search for and discover new books
        - Manage their reading lists (To Read, Currently Reading, Finished)
        - Discuss books, authors, themes, and literary topics

        When a user wants to add a book:
        1. Search for it first to get the Google Books ID
        2. Confirm the correct book with the user if multiple results
        3. Then add it to their requested list
        4. If the book is already in another list, mention that it is already present and ask if they want to move it instead

        When moving a book between lists, ask which list they want it moved to
        if they haven't specified.

        Keep responses friendly and concise.
        If asked about something unrelated to books, politely redirect.
      `,
      tools: [searchBooksTool, ...listsTools],
      generateContentConfig: {
        maxOutputTokens: 1024,
      },
    });
  }

  async chat(
    userId: string,
    message: string,
    sessionId: string,
  ): Promise<string> {
    const agent = this.createAgent(userId);

    const runner = new Runner({
      agent,
      appName: APP_NAME,
      sessionService: this.sessionService,
    });

    const session = await this.sessionService.getSession({
      appName: APP_NAME,
      userId,
      sessionId,
    });

    if (!session) {
      await this.sessionService.createSession({
        appName: APP_NAME,
        userId,
        sessionId,
      });
    }

    const newMessage: Content = {
      role: 'user',
      parts: [{ text: message }],
    };

    let responseText = '';

    for await (const event of runner.runAsync({
      userId,
      sessionId,
      newMessage,
    })) {
      if (event.errorCode) {
        throw new Error(
          event.errorMessage || `Agent error: ${event.errorCode}`,
        );
      }
      if (isFinalResponse(event)) {
        const text = event.content?.parts?.[0]?.text;
        if (text) responseText = text;
      }
    }

    if (!responseText) {
      throw new Error('No response generated by agent');
    }

    return responseText;
  }
}
